# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://cusehacks.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "CuseHacks | April 21- 22nd | Location: Lifesciences Complex, Syracuse University"
  description: "This will be Syracuse University's first student-run hackathon."
  image:       "/images/logo.jpeg"
  # "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "CuseHacks"
  description: "This will be Syracuse University's first student-run hackathon."
  date:        "April 21-22, 2018"
  location:    "Syracuse, NY, United States"
  school:      "Syracuse University"

  trust_badge:
    year:   "2018"  # season year
    region: "na"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        href: "https://goo.gl/forms/8NJ5UwPvj3KyGxLJ2"
        # my_mlh:
        #   client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
        #   redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "/assets/CuseHacks2018_Sponsorship_Package.pdf"

  about:
    description: >
      CuseHacks is the first student-run hackathon at Syracuse University. Over a span of 24-hours, students of all backgrounds are invited
      to explore the possiblities of technology and imagination.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "LEARN."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image2.png"
        title: "BUILD."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
        CuseHacks is not your typical hackathon. We encourage students with any level of experience to sign up. By including the participation of middle school and
        highschool students, we are focused on providing a more welcoming environment to introduce the younger generation to tech culture.
    - question: "How much does it cost?"
      answer: >
        Nothing. Attending a hackathon is free, and we will provide meals, snacks, and swag throughout the event.
    - question: "Who can participate?"
      answer: >
        All current college, high school, and middle school students are invited to participate. We will be capping attendance, so please register ASAP!
    - question: "Will there be travel reimbursement?"
      answer: >
        We can not ensure travel reimbursements right now, but it may be a possibility. Please email cusehacks@gmail for more information.
    - question: "What if I don't have coding or hackathon experience?"
      answer: >
        Beginners are especially encouraged to come! You do not need previous hackathon/coding experience or a technology
        background. CuseHacks is meant to be a comfortable learning experience for everyone. Also, there will be workshops
        and mentors available throughout the event that can help you get started.
    - question: "How do teams work?"
      answer: >
        Each team can have up to as many members as you want. Typically teams run from 3-4 members. You can come with your friends or you can form a team at the event.
        There will be team forming activities at the beginning of the hackathon for anybody interested. You can also work alone if you want.
    - question: "Where is the event?"
      answer: >
        The event will be held in the Life Science Complex Building at Syracuse University.
    - question: "Your question not here?"
      answer: >
        Please email cusehacks@gmail.com for any more questions.

#    - question: "What is Major League Hacking?"
#      answer: >
#        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
#        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
